# Generated by Django 4.2.3 on 2023-08-25 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aghsat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mablagh', models.BigIntegerField()),
                ('tarikh', django_jalali.db.models.jDateField()),
                ('pardakht', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('shomareh', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfighDoreh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.IntegerField(null=True)),
                ('mablagh', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doreh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.IntegerField(null=True)),
                ('tarikh', django_jalali.db.models.jDateField()),
                ('configh', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modir.confighdoreh')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mablagh', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MSandogh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mojodi', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tybeName', models.CharField(max_length=150)),
                ('tedadAghsat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zakhireh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mablagh', models.BigIntegerField()),
                ('pardakht', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('doreh', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modir.doreh')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.member')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', django_jalali.db.models.jDateField()),
                ('mablagh', models.BigIntegerField()),
                ('state', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.member')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.typeloan')),
            ],
        ),
        migrations.CreateModel(
            name='DarkhastSandogh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=200)),
                ('acceptDate', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('deletDate', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('startDate', django_jalali.db.models.jDateField()),
                ('Zakhireh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.zakhireh')),
            ],
        ),
        migrations.CreateModel(
            name='Darkhast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=200)),
                ('acceptDate', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('deletDate', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('startDate', django_jalali.db.models.jDateField()),
                ('Aghsat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.aghsat')),
            ],
        ),
        migrations.AddField(
            model_name='aghsat',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.loan'),
        ),
    ]
