# Generated by Django 4.2.3 on 2023-08-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doreh',
            name='titel',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
