# Generated by Django 4.2.3 on 2023-08-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0003_alter_confighdoreh_titel_alter_doreh_titel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakhireh',
            name='doreh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.doreh'),
        ),
    ]
