# Generated by Django 4.2.3 on 2023-08-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0004_alter_zakhireh_doreh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doreh',
            name='configh',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modir.confighdoreh'),
        ),
    ]
