# Generated by Django 4.2.3 on 2023-07-27 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aghsat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mablagh', models.BigIntegerField()),
                ('tarikh', models.DateField(blank=True)),
                ('pardakht', models.DateField()),
                ('shomareh', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tybeName', models.CharField(max_length=150)),
                ('tedadAghsat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mablagh', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mablagh', models.BigIntegerField()),
                ('tarikh', models.DateField()),
                ('state', models.BooleanField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.member')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.typeloan')),
            ],
        ),
        migrations.CreateModel(
            name='Darkast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=200)),
                ('acceptDate', models.DateField()),
                ('deletDate', models.DateField()),
                ('startDate', models.DateField()),
                ('Aghsat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.aghsat')),
            ],
        ),
        migrations.AddField(
            model_name='aghsat',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.loan'),
        ),
    ]
