# Generated by Django 4.2.3 on 2023-07-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aghsat',
            name='tarikh',
            field=models.DateField(),
        ),
    ]
