# Generated by Django 4.2.3 on 2023-07-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0003_alter_aghsat_pardakht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aghsat',
            name='pardakht',
            field=models.DateField(blank=True, null=True),
        ),
    ]
