# Generated by Django 4.2.3 on 2023-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0004_alter_aghsat_pardakht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkast',
            name='acceptDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='darkast',
            name='deletDate',
            field=models.DateField(null=True),
        ),
    ]
