# Generated by Django 4.2.3 on 2023-07-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0005_alter_darkast_acceptdate_alter_darkast_deletdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkast',
            name='acceptDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darkast',
            name='deletDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
