# Generated by Django 4.2.3 on 2023-07-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0006_alter_darkast_acceptdate_alter_darkast_deletdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
