# Generated by Django 4.2.3 on 2023-08-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0007_alter_loan_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Darkast',
            new_name='Darkhast',
        ),
    ]
