# Generated by Django 4.2.3 on 2023-08-11 15:42

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0008_rename_darkast_darkhast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='tarikh',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
