# Generated by Django 4.2.3 on 2023-08-11 21:08

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0010_alter_aghsat_tarikh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkhast',
            name='acceptDate',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darkhast',
            name='deletDate',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darkhast',
            name='startDate',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
