# Generated by Django 4.2.3 on 2023-08-12 02:59

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0011_alter_darkhast_acceptdate_alter_darkhast_deletdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aghsat',
            name='pardakht',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
