# Generated by Django 4.2.3 on 2023-08-13 20:20

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0013_msandogh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doreh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', django_jalali.db.models.jDateField()),
            ],
        ),
    ]
