# Generated by Django 4.2.3 on 2023-08-15 20:02

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0014_doreh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakhireh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mablgh', models.BigIntegerField()),
                ('pardakht', django_jalali.db.models.jDateField()),
                ('doreh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.doreh')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.member')),
            ],
        ),
    ]
