# Generated by Django 4.2.3 on 2023-08-16 19:58

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0015_zakhireh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakhireh',
            name='pardakht',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
