# Generated by Django 4.2.3 on 2023-08-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0016_alter_zakhireh_pardakht'),
    ]

    operations = [
        migrations.AddField(
            model_name='doreh',
            name='titel',
            field=models.IntegerField(null=True),
        ),
    ]
