# Generated by Django 4.2.3 on 2023-08-17 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0017_doreh_titel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zakhireh',
            old_name='Mablgh',
            new_name='mablgh',
        ),
    ]
