# Generated by Django 4.2.3 on 2023-08-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0018_rename_mablgh_zakhireh_mablgh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zakhireh',
            old_name='mablgh',
            new_name='mablagh',
        ),
    ]
