# Generated by Django 4.2.3 on 2023-08-17 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0019_rename_mablgh_zakhireh_mablagh'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkhast',
            name='Zakhireh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modir.zakhireh'),
        ),
        migrations.AlterField(
            model_name='darkhast',
            name='Aghsat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modir.aghsat'),
        ),
    ]
