# Generated by Django 4.2.3 on 2023-08-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0020_darkhast_zakhireh_alter_darkhast_aghsat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darkhast',
            name='Zakhireh',
        ),
    ]
