# Generated by Django 4.2.3 on 2023-08-17 19:43

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0021_remove_darkhast_zakhireh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkhast',
            name='Aghsat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.aghsat'),
        ),
        migrations.CreateModel(
            name='DarkhastSanogh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=200)),
                ('acceptDate', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('deletDate', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('startDate', django_jalali.db.models.jDateField()),
                ('Zakhireh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modir.zakhireh')),
            ],
        ),
    ]
