# Generated by Django 4.2.3 on 2023-08-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0022_alter_darkhast_aghsat_darkhastsanogh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DarkhastSanogh',
        ),
    ]
