# Generated by Django 4.2.3 on 2023-08-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0024_darkhastsanogh'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DarkhastSanogh',
            new_name='DarkhastSandogh',
        ),
    ]
