# Generated by Django 4.2.3 on 2023-08-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0025_rename_darkhastsanogh_darkhastsandogh'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bedehi',
            field=models.BigIntegerField(default=0),
        ),
    ]
