# Generated by Django 4.2.3 on 2023-08-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0026_member_bedehi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bedehi',
        ),
    ]
