# Generated by Django 4.2.3 on 2023-08-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0027_remove_member_bedehi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoungighDoreh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.IntegerField(null=True)),
                ('mablagh', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='zakhireh',
            name='doreh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modir.doreh'),
        ),
    ]
