# Generated by Django 4.2.3 on 2023-08-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0028_coungighdoreh_alter_zakhireh_doreh'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoungighDoreh',
            new_name='ConfighDoreh',
        ),
    ]
