# Generated by Django 4.2.3 on 2023-08-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0029_rename_coungighdoreh_confighdoreh'),
    ]

    operations = [
        migrations.AddField(
            model_name='doreh',
            name='configh',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='modir.confighdoreh'),
        ),
    ]
