# Generated by Django 4.2.3 on 2023-08-25 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0030_doreh_configh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doreh',
            name='configh',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modir.confighdoreh'),
        ),
    ]
